encoding: utf-8
name: Rahul Vigneswaran k
url: http://rahulvigneswaran.github.io
author:
  name: Rahul Vigneswaran K
  email: rahulvigneswaran@gmail.com
description: Research Assistant at IITH.
permalink: /posts/:title/
include: ['_pages']
